scrape_configs:
  - job_name: mysql_server1
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ["mysqlexporter:9104"]
  - job_name: node_exporter
    static_configs:
      - targets:
          - "node_exporter:9100"
  # - job_name: mysql_server2
  #   metrics_path: /metrics
  #   scrape_interval: 10s
  #   scrape_timeout: 10s
  #   static_configs:
  #     - targets: ["mysqlexporter2:9104"]


